services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Our Microservices
  order-service:
    build:
      context: .
      dockerfile: ./apps/order-service/Dockerfile
    container_name: order-service
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      - kafka
      - mongo

  invoice-service:
    build:
      context: .
      dockerfile: ./apps/invoice-service/Dockerfile
    container_name: invoice-service
    env_file:
      - .env
    ports:
      - "3002:3000"
    depends_on:
      - kafka
      - mongo
    volumes:
    - invoice-uploads:/app/uploads/invoices

volumes:
  mongo-data:
  invoice-uploads: