name: CI Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: ecommerce-test
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.runCommand({ping: 1}).ok' || mongo --quiet --eval 'db.runCommand({ping: 1}).ok'"
          --health-interval 15s
          --health-timeout 15s
          --health-retries 15
          --health-start-period 30s
          
      zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          
      kafka:
        image: confluentinc/cp-kafka:7.3.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "kafka-topics --bootstrap-server localhost:9092 --list"
          --health-interval 30s
          --health-timeout 15s
          --health-retries 10
          --health-start-period 60s
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run linting
        run: pnpm run lint
        
      - name: Check code formatting
        run: pnpm run format --check
        
      - name: Build applications
        run: pnpm run build
        
      - name: Run unit tests
        run: pnpm run test:unit
        
      - name: Verify services are ready
        run: |
          echo "Verifying services are healthy..."
          
          echo "Testing MongoDB connection (should be healthy due to health checks)..."
          nc -z localhost 27017 && echo "✓ MongoDB port is open" || echo "✗ MongoDB port check failed"
          
          echo "Testing Kafka connection (should be healthy due to health checks)..."
          nc -z localhost 9092 && echo "✓ Kafka port is open" || echo "✗ Kafka port check failed"
          
          echo "Services verification completed!"
        
      - name: Run E2E tests
        run: pnpm run test:e2e
        env:
          MONGODB_URL: mongodb://localhost:27017/ecommerce-test
          KAFKA_BROKER_URL: localhost:9092
